name: APK 打包与发布

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.2.3)'
        required: false
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: 设置 Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 打包 APK
        run: |
          chmod +x gradlew
          ./gradlew assembleCiRelease

      - name: 发布至 GitHub Release
        if: |
          github.event_name == 'push' ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.tag)
        uses: softprops/action-gh-release@v2
        with:
          # 推 tag 时取 ref_name；手动触发时取用户输入
          tag_name: ${{ github.event_name == 'push' && github.ref_name || github.event.inputs.tag }}
          files: |
            app/build/outputs/apk/ci/release/*.apk
          token: ${{ secrets.GITHUB_TOKEN }}
