name: APK 打包与发布

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: 设置 Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 打包 APK
        run: |
          chmod +x gradlew
          ./gradlew assembleCiRelease

      - name: 发布至 GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: app/build/outputs/apk/ci/release/*.apk
          token: ${{ secrets.GITHUB_TOKEN }}
